# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160603044730 on 2016-06-07 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
